### ISSUE TITLE
Schema Registry Support

### ISSUE THREAD

**Issue by CliffWheadon** [jbvmio/kafkactl#1]
A lot of kafka users will probably be on the Confluent Platform and dealing with [Avro](https://avro.apache.org/) and the [Schema Registry](https://github.com/confluentinc/schema-registry). 

Using curl to interact with the Schema Registry is cumbersome and doesn't produce the most readable output.

Schema Registry support would be a neat addition to this tool.

**Comment by jbvmio** [comment]
Thanks for the insight @CliffWheadon  - I will definitely look into it after the next release.

**Comment by jbvmio** [comment]
backburner for now.
