### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by joostdecock** [jbvmio/kafkactl#2]
I've been using kafkactl setting up a kafka cluster and finding it very useful, thanks a bunch.

Now I want to put this thing in production, and that includes only listening on SSL.
But unless I'm missing something, it seems kafkactl will only connect to brokers over plaintext.

Is SSL support something that's on the roadmap? The todo lists *Add Security Features* but that could be many things.

Thank you for considering adding SSL support.

**Comment by jbvmio** [comment]
@joostdecock - If you are using the [latest release](https://github.com/jbvmio/kafkactl/releases/latest) I added initial implementation for SASL. Can you try adding the following to your config for the context you need SSL for:

```
  devel-cluster:
    name: devel-cluster
    brokers:
    - devel01.example.com:9092
    - devel02.example.com:9092
    - devel03.example.com:9092
    zookeeper:
    - devel01.example.com:2181
    - devel02.example.com:2181
    - devel03.example.com:2181
    clientVersion: 2.1.1
    sasl:
      insecure: true
      tlscert: /path/to/cert.pem
      tlsca: /path/to/ca.pem
      tlskey: /path/to/key.pem
      username: USER
      password: PASS
```

**Comment by joostdecock** [comment]
Ok, I'll give that a go and I'll report back.

**Comment by joostdecock** [comment]
I had some time to take this for a spin. It didn't work for my use-case, but that's probably because I am not using SASL for authentication, I am use SSL client certificates.

As such, I guess it's not surprise that it doesn't work: 

```
root@ac74b0f51567:~# kafkactl --cfg /etc/kafkactl/config.yaml -v                                                                                             
INFO[2019-10-23T07:31:13Z] Connected to broker at 10.120.220.25:9093 (unregistered)                                                                          
INFO[2019-10-23T07:31:13Z] Connected to broker at 10.120.220.25:9093 (unregistered)                                                                          
WARN[2019-10-23T07:31:13Z] unexpected EOF                                                                                                                    
INFO[2019-10-23T07:31:13Z] Initializing new client                                                                                                           
INFO[2019-10-23T07:31:13Z] client/metadata fetching metadata for all topics from broker 10.120.220.27:9093                                                   
INFO[2019-10-23T07:31:13Z] Invalid SASL Mechanism : kafka server: Request is not valid given the current SASL state.                                         
INFO[2019-10-23T07:31:13Z] Error while performing SASL handshake 10.120.220.27:9093                                                                          
INFO[2019-10-23T07:31:13Z] Closed connection to broker 10.120.220.27:9093                                                                                    
INFO[2019-10-23T07:31:13Z] client/metadata got error from broker -1 while fetching metadata: kafka server: Request is not valid given the current SASL state.
INFO[2019-10-23T07:31:13Z] client/metadata fetching metadata for all topics from broker 10.120.220.26:9093                                                   
INFO[2019-10-23T07:31:13Z] Invalid SASL Mechanism : kafka server: Request is not valid given the current SASL state.                                         
INFO[2019-10-23T07:31:13Z] Error while performing SASL handshake 10.120.220.26:9093                                                                          
INFO[2019-10-23T07:31:13Z] Closed connection to broker 10.120.220.26:9093                                                                                    
INFO[2019-10-23T07:31:13Z] client/metadata got error from broker -1 while fetching metadata: kafka server: Request is not valid given the current SASL state.
INFO[2019-10-23T07:31:13Z] client/metadata fetching metadata for all topics from broker 10.120.220.25:9093                                                   
INFO[2019-10-23T07:31:13Z] Invalid SASL Mechanism : kafka server: Request is not valid given the current SASL state.                                         
INFO[2019-10-23T07:31:13Z] Error while performing SASL handshake 10.120.220.25:9093                                                                          
INFO[2019-10-23T07:31:13Z] Closed connection to broker 10.120.220.25:9093                                                                                    
INFO[2019-10-23T07:31:13Z] client/metadata got error from broker -1 while fetching metadata: kafka server: Request is not valid given the current SASL state.
INFO[2019-10-23T07:31:13Z] client/metadata no available broker to send metadata request to                                                                   
INFO[2019-10-23T07:31:13Z] client/brokers resurrecting 3 dead seed brokers                                                                                   
```

On the kafka side, I get:

```
[2019-10-23 07:31:13,638] INFO [SocketServer brokerId=1026] Failed authentication with /172.18.0.1 (SSL handshake failed) (org.apache.kafka.common.network.Selector)
```

I get similar errors for other client certificate issues (missing chain and so on). However, the certificate/key I tested with here works fine for other clients, so I know it's ok.
To confirm this, I enabled SSL handshake debugging in Kafka, and I can see it seems to end fine:

```
*** CertificateVerify
Signature Algorithm SHA512withRSA
data-plane-kafka-network-thread-1032-ListenerName(SSL)-SSL-2, READ: TLSv1.2 Change Cipher Spec, length = 1
update handshake state: change_cipher_spec
upcoming handshake states: client finished[20]
upcoming handshake states: server change_cipher_spec[-1]
upcoming handshake states: server finished[20]
data-plane-kafka-network-thread-1032-ListenerName(SSL)-SSL-2, READ: TLSv1.2 Handshake, length = 40
check handshake state: finished[20]
update handshake state: finished[20]
upcoming handshake states: server change_cipher_spec[-1]
upcoming handshake states: server finished[20]
*** Finished
```

So it seems (to me) that the client certificate authentication is working fine. But then it tries to do SASL authentication, which is not what is expected for my use-case.

So I think I would have two feature requests:

**Allow SSL wilthout SASL**

Removing `username` and `password` from the configuration makes kafkactl throw:

```
Error: kafka: invalid configuration (Net.SASL.User must not be empty when SASL is enabled)
```

Would it be possible to enable the use of SSL without SASL? Perhaps setup a `ssl` configuration block that is separate from the `sasl` settings?

**Allow encrypted private keys**

I prefer to keep configuration under version control. This includes encrypted private keys (protected by a passphrase). This is currently not supported, because [LoadX509KeyPair can't parse a password protected pem file](https://github.com/golang/go/issues/10181). 

My Go skills are none-existent, but I'd be happy to help in any way I can,

**Comment by jbvmio** [comment]
@joostdecock - I appreciate the testing and thorough details. If you find some more time, I'd appreciate if you could repeat trying this [beta release](https://github.com/jbvmio/kafkactl/releases/tag/v1.0.24-beta.25544104) using the following for your config:
```
  devel-cluster:
    name: devel-cluster
    brokers:
    - devel01.example.com:9092
    - devel02.example.com:9092
    - devel03.example.com:9092
    zookeeper:
    - devel01.example.com:2181
    - devel02.example.com:2181
    - devel03.example.com:2181
    clientVersion: 2.1.1
    ssl:
      insecure: true
      tlscert: /path/to/cert.pem
      tlsca: /path/to/ca.pem
      tlskey: /path/to/key.pem
    sasl:
      username: USER
      password: PASS
```
I separated the SSL / SASL logic and blocks as you have suggested. Feel free to omit the sasl block entirely if not needed.

**Comment by joostdecock** [comment]
Wow, that was fast :)
I will try this asap and get back with my findings.

Thanks!

**Comment by joostdecock** [comment]
Here's what I've learned: `v1.0.24-beta.25544104` works flawlessly for SSL encrypted connections with client certificate authentication (no SASL) :heart: 

I've included some info below for the benefit of others who might be reading this.

Here is my (slightly REDACTED) config file:

```yaml
contexts:                              
  lan:                                 
    name: lan                          
    brokers:                           
      - 1.REDACTED:9093  
      - 2.REDACTED:9093  
      - 3.REDACTED:9093  
    zookeeper:                         
      - 1.REDACTED:2182  
      - 2.REDACTED:2182  
      - 3.REDACTED:2182  
    clientVersion: 2.1.1               
    ssl:                               
      insecure: false                  
      tlscert: /etc/kafkactl/client.crt
      tlsca: /etc/kafkactl/ca.crt
      tlskey: /etc/kafkactl/clear.key  
current-context: lan                   
config-version: 1                      
```

Note that:

 - I have redacted the host names because work
 - I have configured **port 9093** as port 9092 is typically for plaintext connections
 - I have set `ssl.insecure` to `false`. My assumption is that setting this to `true` will forego validation of the broker certificate, but given that my broker certificates are valid, I don't need that. Note that I've tested this with `true` and `false` and both work.

I run kafkactl in a container that wraps the binary. To make life a bit easier, I created a bash alias so that I can just use `kafkactl`. Here's the alias setup:

```bash
alias kafkactl="sudo docker run --rm -v /etc/kafkactl:/etc/kafkactl -v /etc/kafkactl/config.yaml:/root/.kafkactl.yaml jbvmio/kafkactl:v1.0.24-beta.25544104"
```

 - I'm mounting the `/etc/kafkactl` volume as `/etc/kafkactl` (that's the directory where I store the client certificate, key, and CA). 
 - I'm mounting the `/etc/kafkactl/config.yaml` file as `/root/.kafkactl.yaml` as that's where it looks for the config file by default. An alternative approach here would be to specify the config file location by passing it with the `--cfg` flag to kafkactl

With this alias in place, things *just work* when I run `kafkactl`:

```bash
kafkactl                  
                                     
Brokers:  3                          
 Topics:  0                          
 Groups:  0                          
                                     
Client:  (Using: 2.1.1)              
Cluster: (Kafka: 2.1.0)              
* 1.REDACTED:9093/1001 
  2.REDACTED:9093/1002 
  3.REDACTED:9093/1003 
                                     
(*)Controller                        
```

Getting/Creating topics is fine too:

```bash
kafkactl get topics                                         
No Topics Seem to Exist.                                               

kafkactl admin create topic --replicas 3 --partitions 3 test
Successfully created topic test                                        

kafkactl get topics                                         
                                                                       
TOPIC  PART  RFactor  ISRs  OFFLINE                                    
test   0-2   3        9     0                                          
```

Given that everything works, I did not include any debug output.

Thank you for adding this on such short notice, you're a :star:

**Comment by jbvmio** [comment]
Excellent report @joostdecock. I really appreciate all the testing and feedback, it has been very helpful!

**Comment by jbvmio** [comment]
Changes have been integrated into [release v1.0.25](https://github.com/jbvmio/kafkactl/releases/tag/v1.0.25)
