### ISSUE TITLE
build broken on termui dependency

### ISSUE THREAD

**Issue by nergdron** [jbvmio/kafkactl#3]
when attempting to build today on go 1.13, I get the following dependency error:

```
 go build -o $GOPATH/bin/kafkactl
build github.com/jbvmio/kafkactl: cannot load github.com/gizak/termui: module github.com/gizak/termui@latest (v3.1.0+incompatible) found, but does not contain package github.com/gizak/termui
```

**Comment by jbvmio** [comment]
@nergdron - What version is set in your go.mod file? You may need to set the version to

`github.com/gizak/termui v2.2.1-0.20180111180145-a433c24293cf+incompatible`

**Comment by nergdron** [comment]
oh yeah, you're right, the file had been updated from what was in the repo. I checked out the copy from the repo and did a go get and go build, and it looks happier now. so not a bug!

**Comment by jbvmio** [comment]
Thanks for the follow up!
