### ISSUE TITLE
--json-filter example?

### ISSUE THREAD

**Issue by terebentina** [jbvmio/kafkactl#8]
Hi,

I can't figure out how `--json-filter` is supposed to work to filter the messages as I follow a topic. 
Could you, please, show an example?
Thank you!

**Comment by jbvmio** [comment]
I originally was going to flesh this feature out some more before I showed some examples, but then it kind've fell to the wayside with some other projects. I went ahead and posted some examples of how it currently works here:

https://github.com/jbvmio/kafkactl/wiki/JSONFilter

**Comment by terebentina** [comment]
Perfect, thanks!
